---

- name: Install OpenSCAP and required packages
  ansible.builtin.package:
    name:
      - openscap-scanner
      - scap-security-guide
      - openscap-utils
      - jq
    state: present

- name: Ensure output directory exists
  ansible.builtin.file:
    path: "{{ hardener_output_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
